"""
FlexEdgeAdmin — TLS Renewal scheduler.

Provides:
  - Webhook handler for certbot's deploy-hook (POST /tls/api/renew)
  - Periodic check (call from a cron job or manually)
  - Hook script generator
"""
import hashlib
import logging
import shlex
from pathlib import Path

from shared.db import db
from webapp.models import ManagedCertificate, TLSDeployment
from webapp.tls_deployer import run_deployment

logger = logging.getLogger(__name__)


def cert_file_hash(lineage_path: str) -> str:
    fullchain = Path(lineage_path) / "fullchain.pem"
    if not fullchain.exists():
        return ""
    h = hashlib.sha256()
    with open(fullchain, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def handle_renewal_webhook(domain: str) -> dict:
    """Re-deploy all active deployments tied to a domain's certificate.

    Cross-Domain by design (Domain-Scoping Audit, exception E2): the
    certbot renewal hook fires at host level, not Domain level, so a
    single cert lineage may legitimately fan out to engines across
    multiple FlexEdgeAdmin Domains. To keep the audit trail honest,
    this emits ONE audit row per affected Domain with
    `feature="tls"`, `action="renew.cross_domain"`, the Domain id and
    the count of redeployments. Operators reading `/logs` in any one
    Domain see exactly the renewal actions that touched THEIR engines,
    not a global "the cert renewed" line for the whole host.
    """
    cert = ManagedCertificate.query.filter_by(domain=domain).first()
    if not cert:
        return {"error": f"No managed certificate for domain: {domain}", "renewed": 0}

    cert.last_cert_hash = cert_file_hash(cert.certbot_lineage)
    db.session.commit()

    deps = TLSDeployment.query.filter_by(
        certificate_id=cert.id, auto_renew=True,
    ).all()

    results = []
    # Per-Domain bucket so we can emit one audit row per Domain at the
    # end with its own count + status breakdown.
    by_domain: dict[int, dict] = {}
    for dep in deps:
        if not dep.tenant.is_active or not dep.api_key.is_active:
            results.append({
                "deployment_id": dep.id, "status": "skipped",
                "reason": "inactive tenant or API key",
            })
            bucket = by_domain.setdefault(
                dep.domain_id or 0,
                {"deployed": 0, "failed": 0, "skipped": 0, "engines": []},
            )
            bucket["skipped"] += 1
            continue
        result = run_deployment(dep.id, action="renew")
        outcome = "deployed" if result.success else "failed"
        results.append({
            "deployment_id": dep.id,
            "service_name": dep.service_name,
            "engine": dep.engine_name,
            "status": outcome,
            "error": result.error,
            "steps": result.steps,
        })
        bucket = by_domain.setdefault(
            dep.domain_id or 0,
            {"deployed": 0, "failed": 0, "skipped": 0, "engines": []},
        )
        bucket[outcome] += 1
        bucket["engines"].append(dep.engine_name)

    # One audit row per Domain affected by this renewal.
    try:
        from shared.logging import audit
        for did, b in by_domain.items():
            engines = ", ".join(sorted(set(b["engines"])))[:200]
            status = "ok" if b["failed"] == 0 else (
                "partial" if b["deployed"] > 0 else "failed")
            audit("tls", "renew.cross_domain",
                  status=status,
                  target=domain,                      # the DNS hostname (cert lineage)
                  detail=(f"deployed={b['deployed']} failed={b['failed']} "
                          f"skipped={b['skipped']} engines=[{engines}]"),
                  domain_id=did or None,              # FEA Domain — None for legacy rows
                  source_correlation_id=f"tls-renew-{cert.id}")
    except Exception as exc:
        logger.warning("audit emission failed for renewal of %s: %s", domain, exc)

    return {"domain": domain, "renewed": len(results), "results": results}


def check_all_certificates() -> list:
    """Scan tracked certificates and redeploy any whose fullchain.pem changed."""
    changed = []
    for cert in ManagedCertificate.query.all():
        current = cert_file_hash(cert.certbot_lineage)
        if current and current != cert.last_cert_hash:
            logger.info("Cert changed for %s", cert.domain)
            changed.append(handle_renewal_webhook(cert.domain))
    return changed


DEPLOY_HOOK_TEMPLATE = """#!/bin/bash
# Auto-generated by FlexEdgeAdmin TLS Manager
# Place in /etc/letsencrypt/renewal-hooks/deploy/ or pass via:
#   certbot renew --deploy-hook /path/to/this/script.sh
#
# M3 (audit fix-up, 2026-05-09) — the bearer token lives in a SIBLING
# file with chmod 0600 (root only); this script chmod 0700 sources it
# at runtime. The previous pattern baked the token directly into the
# script body which was chmod 0755 — any local process could read it.

set -e

DOMAIN=$(echo "$RENEWED_DOMAINS" | awk '{{print $1}}')
API_URL="{api_url}"
TOKEN_FILE="{token_file}"

if [ ! -r "$TOKEN_FILE" ]; then
    echo "TLS renewal hook: cannot read $TOKEN_FILE — refusing to call API." >&2
    exit 1
fi
# shellcheck disable=SC1090
. "$TOKEN_FILE"
if [ -z "${{FLEXEDGE_TLS_API_TOKEN:-}}" ]; then
    echo "TLS renewal hook: $TOKEN_FILE did not export FLEXEDGE_TLS_API_TOKEN." >&2
    exit 1
fi

curl -s -X POST "$API_URL/tls/api/renew" \\
    -H "Content-Type: application/json" \\
    -H "Authorization: Bearer $FLEXEDGE_TLS_API_TOKEN" \\
    -d "{{\\"domain\\": \\"$DOMAIN\\"}}"

echo "TLS renewal hook executed for $DOMAIN"
"""


def generate_deploy_hook(api_url: str, token_file: str) -> str:
    """Render the bash script body. `token_file` is the absolute path the
    script will `source` at runtime to import `FLEXEDGE_TLS_API_TOKEN`.
    """
    return DEPLOY_HOOK_TEMPLATE.format(api_url=api_url, token_file=token_file)


def generate_token_file(api_token: str) -> str:
    """Render the contents of the sibling 0600 token file.

    M3 (audit fix-up, 2026-05-09): kept as a separate helper so the
    /tls/hook page can show the operator both files for manual install
    on hosts where the auto-installer can't reach
    `/etc/letsencrypt/renewal-hooks/deploy/`.
    """
    return (
        "# Auto-generated by FlexEdgeAdmin TLS Manager — do not edit.\n"
        "# Sourced by flexedge-tls-renew.sh; chmod 0600 on disk.\n"
        f"export FLEXEDGE_TLS_API_TOKEN={shlex.quote(api_token)}\n"
    )


# Default path used by the `/tls/hook` page so the operator sees the same
# token-file path the auto-installer would use. Override at install time
# via the `hook_dir` form field.
DEFAULT_TOKEN_FILE = "/etc/letsencrypt/renewal-hooks/deploy/flexedge-tls-renew.sh.token"


def install_deploy_hook(api_url: str, api_token: str,
                        hook_dir: str = "/etc/letsencrypt/renewal-hooks/deploy") -> str:
    """Install the deploy hook + sibling 0600 token file.

    M3 (audit fix-up, 2026-05-09):
      * Hook script: chmod 0700 (was 0755). Only root can read/execute.
      * Token file: chmod 0600, lives next to the hook with the
        sentinel name `<hook>.token`. Sourced at runtime — never
        appears in the script body or in process arguments.
    """
    hook_path = Path(hook_dir) / "flexedge-tls-renew.sh"
    token_path = hook_path.with_name(hook_path.name + ".token")
    hook_path.parent.mkdir(parents=True, exist_ok=True)

    # Token file first — write atomically (write-then-chmod-then-rename
    # would be cleaner, but Python's Path.write_text doesn't support
    # mode-on-create; touch+chmod+write avoids the brief 0644 window.
    token_path.touch(mode=0o600, exist_ok=True)
    token_path.chmod(0o600)
    token_path.write_text(
        f'# Auto-generated by FlexEdgeAdmin TLS Manager — do not edit.\n'
        f'# Sourced by {hook_path.name}; rotate by re-installing the hook.\n'
        f'export FLEXEDGE_TLS_API_TOKEN={shlex.quote(api_token)}\n'
    )
    # Re-chmod after write_text (some platforms reset the mode on
    # truncation when the file already existed with a wider mode).
    token_path.chmod(0o600)

    # Hook script — references the token file by absolute path.
    hook_path.write_text(generate_deploy_hook(api_url, str(token_path)))
    hook_path.chmod(0o700)
    return str(hook_path)
