"""
FlexEdgeAdmin — TLS Renewal scheduler.

Provides:
  - Webhook handler for certbot's deploy-hook (POST /tls/api/renew)
  - Periodic check (call from a cron job or manually)
  - Hook script generator
"""
import hashlib
import logging
from pathlib import Path

from shared.db import db
from webapp.models import ManagedCertificate, TLSDeployment
from webapp.tls_deployer import run_deployment

logger = logging.getLogger(__name__)


def cert_file_hash(lineage_path: str) -> str:
    fullchain = Path(lineage_path) / "fullchain.pem"
    if not fullchain.exists():
        return ""
    h = hashlib.sha256()
    with open(fullchain, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def handle_renewal_webhook(domain: str) -> dict:
    """Re-deploy all active deployments tied to a domain's certificate."""
    cert = ManagedCertificate.query.filter_by(domain=domain).first()
    if not cert:
        return {"error": f"No managed certificate for domain: {domain}", "renewed": 0}

    cert.last_cert_hash = cert_file_hash(cert.certbot_lineage)
    db.session.commit()

    deps = TLSDeployment.query.filter_by(
        certificate_id=cert.id, auto_renew=True,
    ).all()

    results = []
    for dep in deps:
        if not dep.tenant.is_active or not dep.api_key.is_active:
            results.append({
                "deployment_id": dep.id, "status": "skipped",
                "reason": "inactive tenant or API key",
            })
            continue
        result = run_deployment(dep.id, action="renew")
        results.append({
            "deployment_id": dep.id,
            "service_name": dep.service_name,
            "engine": dep.engine_name,
            "status": "deployed" if result.success else "failed",
            "error": result.error,
            "steps": result.steps,
        })

    return {"domain": domain, "renewed": len(results), "results": results}


def check_all_certificates() -> list:
    """Scan tracked certificates and redeploy any whose fullchain.pem changed."""
    changed = []
    for cert in ManagedCertificate.query.all():
        current = cert_file_hash(cert.certbot_lineage)
        if current and current != cert.last_cert_hash:
            logger.info("Cert changed for %s", cert.domain)
            changed.append(handle_renewal_webhook(cert.domain))
    return changed


DEPLOY_HOOK_TEMPLATE = """#!/bin/bash
# Auto-generated by FlexEdgeAdmin TLS Manager
# Place in /etc/letsencrypt/renewal-hooks/deploy/ or pass via:
#   certbot renew --deploy-hook /path/to/this/script.sh

DOMAIN=$(echo "$RENEWED_DOMAINS" | awk '{{print $1}}')
API_URL="{api_url}"
API_TOKEN="{api_token}"

curl -s -X POST "$API_URL/tls/api/renew" \\
    -H "Content-Type: application/json" \\
    -H "Authorization: Bearer $API_TOKEN" \\
    -d "{{\\"domain\\": \\"$DOMAIN\\"}}"

echo "TLS renewal hook executed for $DOMAIN"
"""


def generate_deploy_hook(api_url: str, api_token: str) -> str:
    return DEPLOY_HOOK_TEMPLATE.format(api_url=api_url, api_token=api_token)


def install_deploy_hook(api_url: str, api_token: str,
                        hook_dir: str = "/etc/letsencrypt/renewal-hooks/deploy") -> str:
    hook_path = Path(hook_dir) / "flexedge-tls-renew.sh"
    hook_path.parent.mkdir(parents=True, exist_ok=True)
    hook_path.write_text(generate_deploy_hook(api_url, api_token))
    hook_path.chmod(0o755)
    return str(hook_path)
