"""
FlexEdgeAdmin — TLS Renewal scheduler.

Provides:
  - Webhook handler for certbot's deploy-hook (POST /tls/api/renew)
  - Periodic check (call from a cron job or manually)
  - Hook script generator
"""
import hashlib
import logging
from pathlib import Path

from shared.db import db
from webapp.models import ManagedCertificate, TLSDeployment
from webapp.tls_deployer import run_deployment

logger = logging.getLogger(__name__)


def cert_file_hash(lineage_path: str) -> str:
    fullchain = Path(lineage_path) / "fullchain.pem"
    if not fullchain.exists():
        return ""
    h = hashlib.sha256()
    with open(fullchain, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def handle_renewal_webhook(domain: str) -> dict:
    """Re-deploy all active deployments tied to a domain's certificate.

    Cross-Domain by design (Domain-Scoping Audit, exception E2): the
    certbot renewal hook fires at host level, not Domain level, so a
    single cert lineage may legitimately fan out to engines across
    multiple FlexEdgeAdmin Domains. To keep the audit trail honest,
    this emits ONE audit row per affected Domain with
    `feature="tls"`, `action="renew.cross_domain"`, the Domain id and
    the count of redeployments. Operators reading `/logs` in any one
    Domain see exactly the renewal actions that touched THEIR engines,
    not a global "the cert renewed" line for the whole host.
    """
    cert = ManagedCertificate.query.filter_by(domain=domain).first()
    if not cert:
        return {"error": f"No managed certificate for domain: {domain}", "renewed": 0}

    cert.last_cert_hash = cert_file_hash(cert.certbot_lineage)
    db.session.commit()

    deps = TLSDeployment.query.filter_by(
        certificate_id=cert.id, auto_renew=True,
    ).all()

    results = []
    # Per-Domain bucket so we can emit one audit row per Domain at the
    # end with its own count + status breakdown.
    by_domain: dict[int, dict] = {}
    for dep in deps:
        if not dep.tenant.is_active or not dep.api_key.is_active:
            results.append({
                "deployment_id": dep.id, "status": "skipped",
                "reason": "inactive tenant or API key",
            })
            bucket = by_domain.setdefault(
                dep.domain_id or 0,
                {"deployed": 0, "failed": 0, "skipped": 0, "engines": []},
            )
            bucket["skipped"] += 1
            continue
        result = run_deployment(dep.id, action="renew")
        outcome = "deployed" if result.success else "failed"
        results.append({
            "deployment_id": dep.id,
            "service_name": dep.service_name,
            "engine": dep.engine_name,
            "status": outcome,
            "error": result.error,
            "steps": result.steps,
        })
        bucket = by_domain.setdefault(
            dep.domain_id or 0,
            {"deployed": 0, "failed": 0, "skipped": 0, "engines": []},
        )
        bucket[outcome] += 1
        bucket["engines"].append(dep.engine_name)

    # One audit row per Domain affected by this renewal.
    try:
        from shared.logging import audit
        for did, b in by_domain.items():
            engines = ", ".join(sorted(set(b["engines"])))[:200]
            status = "ok" if b["failed"] == 0 else (
                "partial" if b["deployed"] > 0 else "failed")
            audit("tls", "renew.cross_domain",
                  status=status,
                  target=domain,                      # the DNS hostname (cert lineage)
                  detail=(f"deployed={b['deployed']} failed={b['failed']} "
                          f"skipped={b['skipped']} engines=[{engines}]"),
                  domain_id=did or None,              # FEA Domain — None for legacy rows
                  source_correlation_id=f"tls-renew-{cert.id}")
    except Exception as exc:
        logger.warning("audit emission failed for renewal of %s: %s", domain, exc)

    return {"domain": domain, "renewed": len(results), "results": results}


def check_all_certificates() -> list:
    """Scan tracked certificates and redeploy any whose fullchain.pem changed."""
    changed = []
    for cert in ManagedCertificate.query.all():
        current = cert_file_hash(cert.certbot_lineage)
        if current and current != cert.last_cert_hash:
            logger.info("Cert changed for %s", cert.domain)
            changed.append(handle_renewal_webhook(cert.domain))
    return changed


DEPLOY_HOOK_TEMPLATE = """#!/bin/bash
# Auto-generated by FlexEdgeAdmin TLS Manager
# Place in /etc/letsencrypt/renewal-hooks/deploy/ or pass via:
#   certbot renew --deploy-hook /path/to/this/script.sh

DOMAIN=$(echo "$RENEWED_DOMAINS" | awk '{{print $1}}')
API_URL="{api_url}"
API_TOKEN="{api_token}"

curl -s -X POST "$API_URL/tls/api/renew" \\
    -H "Content-Type: application/json" \\
    -H "Authorization: Bearer $API_TOKEN" \\
    -d "{{\\"domain\\": \\"$DOMAIN\\"}}"

echo "TLS renewal hook executed for $DOMAIN"
"""


def generate_deploy_hook(api_url: str, api_token: str) -> str:
    return DEPLOY_HOOK_TEMPLATE.format(api_url=api_url, api_token=api_token)


def install_deploy_hook(api_url: str, api_token: str,
                        hook_dir: str = "/etc/letsencrypt/renewal-hooks/deploy") -> str:
    hook_path = Path(hook_dir) / "flexedge-tls-renew.sh"
    hook_path.parent.mkdir(parents=True, exist_ok=True)
    hook_path.write_text(generate_deploy_hook(api_url, api_token))
    hook_path.chmod(0o755)
    return str(hook_path)
